# Generated by Django 2.2.4 on 2019-08-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='2019-08-18',
            field=models.DateField(default='2019-08-19', verbose_name='date_joined'),
            preserve_default=False,
        ),
    ]
