# Generated by Django 2.2.4 on 2019-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190818_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='2019-08-18',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now=True, verbose_name='date_joined'),
        ),
    ]
